### ISSUE TITLE
组件文档补完

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#251]
- [x] Alert (@Justineo)
- [x] AlertBox (@yibuyisheng)
- [x] Breadcrumb & BreadcrumbItem (@yibuyisheng)
- [x] Button (@Justineo)
- [x] ButtonGroup (@Justineo)
- [x] Calendar (@Justineo)
- [x] Carousel (@Justineo)
- [x] CheckButtonGroup (@Justineo)
- [x] Checkbox (@Justineo)
- [x] CheckboxGroup (@Justineo)
- [x] ConfirmBox (@yibuyisheng)
- [x] DatePicker (@Justineo)
- [x] Dialog (@yibuyisheng)
- [x] Dropdown (@Justineo)
- [x] Field (@chestnutchen)
- [x] Fieldset (@chestnutchen)
- [x] Form (@chestnutchen)
- [x] Icon (@Justineo)
- [x] Input (@chestnutchen)
- [x] Label (@chestnutchen)
- [x] Link (@Justineo)
- [x] Overlay (@yibuyisheng)
- [x] Pagination (@599316527)
- [x] Progress (@Justineo)
- [x] PromptBox (@yibuyisheng)
- [x] Radio (@Justineo)
- [x] RadioButtonGroup (@Justineo)
- [x] RadioGroup (@Justineo)
- [x] RegionPicker (@Justineo)
- [x] Schedule (@Justineo)
- [x] Searchbox (@teazean)
- [x] Select & OptionGroup & Option (@Justineo)
- [x] Slider (@599316527)
- [x] Span (@chestnutchen)
- [x] Steps (@Justineo)
- [x] Switch (@Justineo)
- [x] Tabs & Tab (@chestnutchen)
- [x] Table & Column (@Justineo)
- [x] Textarea (@Justineo)
- [x] Toast (@Justineo)
- [x] Tooltip (@Justineo)
- [x] Transfer & FilterPanel (@yibuyisheng)
- [x] Tree (@yibuyisheng)
- [x] Uploader (@r7r10t32)

**Comment by 599316527** [comment]
写法有啥规定吗，在哪儿写

**Comment by Justineo** [comment]
Done 🎉
