### ISSUE TITLE
DLS-18 对齐（一期）

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#459]
### Button (@zhangjialiang)

- [x] 样式调整

### Link (@zhangjialiang)

- [x] 样式调整

### Pagination (@profitfrl)

- [ ] 增加页码跳转功能
- [ ] 样式调整

### Breadcrumbs (@profitfrl)

- [ ] 样式调整

### Anchor

- [ ] 新增

### Steps

- [ ] 增加交互状态
- [ ] 样式调整

### Tree (@r7r10t32)

- [ ] 增加选择功能
- [ ] 样式调整

### Dropdown

- [ ] 多级下拉悬浮触发展开
- [ ] 浮层中搜索功能？
- [ ] 样式调整

### Menu

- [ ] 新增

### DatePicker

- [ ] 样式调整

### Slider

- [ ] 增加 step 说明
- [ ] 样式调整

### TimePicker

- [ ] 新组件

### Transfer (@r7r10t32)

- [ ] 多列穿梭框?
- [ ] 样式调整

### Switch

- [ ] 文字支持？
- [ ] 样式调整

### Checkbox & Radio

- [x] 样式调整

### ButtonGroup, RadioButtonGroup & CheckButtonGroup

- [x] 样式调整

### Select

- [ ] CascadeSelect?
- [ ] MutiSelect?
- [ ] TagInput (@codeDebugTest)
- [ ] 样式调整

### Searchbox

- [ ] 重构，切换到 Autocomplete
- [ ] 样式调整

### NumberInput

- [ ] 新增加强类型
- [ ] 样式调整

### Textarea

- [ ] 字数统计/限制?
- [ ] 样式调整

### Input

- [ ] 字数统计/限制?
- [ ] 样式调整

### Carousel

- [ ] 重构

### Tag (@codeDebugTest)

- [ ] 新增

### Collapse

- [ ] 新增

### Accordion

- [ ] 新增

### Dialog (@eyunhua)

- [ ] 新增 Embedded (inline) 模式
- [ ] 样式调整

### Drawer (@xiaodemen)

- [ ] 新增

### Tooltip

- [ ] 样式调整

### Popover ?

- [ ] 基于 Tooltip？是否必要？

### Dialog

- [ ] 样式调整

### Progress (@weishuping)

- [ ] 样式调整

### Loading (@fengChongxiu)

- [ ] 新增

### Badge

- [ ] 新增

### Toast

- [ ] 新增手动关闭
- [ ] 样式调整

### Alert

- [ ] 样式调整

---

## 新增

Anchor、Menu、TimePicker、Tag、TagInput、Collapse、Accordion、Drawer、Loading、Badge

**Comment by xiaodemen** [comment]
认领 Drawer

**Comment by codeDebugTest** [comment]
-  Tag
-  TagInput

**Comment by eyunhua** [comment]
认领 Dialog

**Comment by Justineo** [comment]
@eyunhua 这个 UE 的标注还没出，现实现新功能吧。`inline` 模式下面，直接在内容中显示（不需要 `Overlay`）。

**Comment by r7r10t32** [comment]
- tree

- transfer

**Comment by zhangjialiang** [comment]
- Button
- Link

**Comment by fengChongxiu** [comment]
- Loading

**Comment by profitfrl** [comment]
认领 Pagination、Breadcrumbs

**Comment by weishuping** [comment]
认领 Progress

**Comment by IceEnd** [comment]
认领

- DatePicker

**Comment by Justineo** [comment]
See #512.
