### ISSUE TITLE
第一批组件待调整的点

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#59]
- [x] `Dialog` 支持无标题栏样式
- [x] `outside` 指令 `hover` 触发时的实现调整为使用 `mouseenter` / `mouseleave`
- [x] `OverlayManager` 实现同 context 浮层的优先级处理
- [x] `Overlay` 在 tether 计算位置之前，设置 `opacity` 为 0
- [x] `DatePicker` 支持快捷选择
- [x] `DatePicker` 支持`disabled/readonly`
- [x] `DatePicker` 时段选择选完开始时间显示已选日期
- [x] `Form` 支持层级`disabled/readonly`
- [x] `Uploader` 支持 `v-model`
- [x] `Select` 组件分隔线支持
- [x] `Select` 组件下拉框截断部分边缘淡出效果
- [x] 去除对 `vue-awesome/icons` 的依赖

「`Form` 支持多提交按钮带参数」暂不实现了。
