### ISSUE TITLE
D20 更新 checklist

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#652]
# D20 改动清单

## Breadcrumb

- [x] 末级（当前级别）增加文字颜色设置

## Button

- [x] 新增加强文字按钮样式 (strong text)
- [x] 新增弱文字按钮样式 (weak text)
- [x] 原来的普通普通 (normal) 改为基础按钮 (basic)，原来子组件使用普通按钮的使用场景改用基础按钮
- [x] 去除图标按钮 (icon)，合并入文字按钮 (text)
- [x] 删除主要按钮组分隔线颜色，普通和主要按钮组合都改为当前文字颜色的透明度实现

## Checkbox

- [x] 加强样式需要调整已选样式
- [x] 对勾改三角

## Collapse

- [x] 内容行高设置

## DatePicker/Calendar

- [x] 新增范围末端按下样式
- [x] 范围中段背景色改为与选择过程中范围末端悬浮背景色一致

## Dropdown

- [x] 删除 split 按钮分隔线颜色，直接使用 ButtonGroup 对应样式

## Form

- [x] 新增 Form 样式

## Icon

- [x] 所有“小图标”需要侧缩小 1P 边距 <待定>

## Input

- [x] 清除按钮与计数器共存场景

## Loading

- [x] 新增可选带遮罩背景色

## Menu

- [x] 横向 Menu 增加菜单下拉、卡片下拉及超长收起
- [x] 纵向 Menu 收起时第一级展开菜单增加上一级导航文字描述
- [x] 纵向 Menu 整体收缩/展开图标更换

## NumberInput

- [x] 按钮图标颜色减弱

## Pagination

- [x] 非当前页码的样式更新，不再直接使用按钮
- [x] 删除了当前样式的变量，直接使用主要按钮的样式

## Popover

- [x] 增加 s/m 号字体设置

## Radio

- [x] 加强样式需要调整已选样式

## Slider

- [x] 默认 Tooltip 样式切换为 reverse

## Switch

- [x] 去除文字内容支持
- [x] 宽度修改

## Table

- [x] 表头、内容使用不同分隔线颜色
- [x] 增加紧凑、宽松（compact/loose）样式
- [x] ~~单行/双行/自适应行高样式~~（使用者自行实现）
- [x] 表格最左/最右侧 padding-x 增大
- [x] 支持表头 Tooltip
- [ ] 表格列宽拖拽
- [x] 纵向分隔线：仅表头、全表
- [x] ~~总计行~~（使用数据行自行扩展）
- [ ] 自定义选择
- [x] 自定义筛选
- [x] 排序样式修改

## Tabs

- [x] 新增 simple/strong 样式
- [x] 移除 segment 样式
- [x] 微调左右滚动按钮、添加按钮的间距

## Tag

- [x] 移除添加按钮样式
- [x] 各种状态切换为使用透明度实现

## Toast

- [x] 上下 padding 不再区分多行/单行 Toast

## Tooltip

- [x] 默认样式与反色样式反转

## Tree

- [x] 展开/收起图标改成三角图标

## Transfer

- [x] 增加项目 disabled 背景色设置（对齐逻辑）

## Uploader

- [x] 文件上传，图标单独配色
- [x] 图片上传，中间图标单独配色
- [x] 错误颜色区分前景色与边框色
- [x] 遮罩层背景改为通过背景色提供而非不透明度
