### ISSUE TITLE
文档更新

### ISSUE THREAD

**Issue by Justineo** [ecomfe/veui#816]
文档有一段时间不更新了，记录下更新点：

- [x] 新增 `Lightbox` 组件
- [x] `Uploader` 组件的 `entries` prop
- [x] `Uploader` 组件新增 `media` 模式
- [x] `Uploader` 组件 `value` prop 类型变化
- [x] `Uploader` 组件的 `preview-options` prop
- [x] `Uploader` 组件的 `multiple` prop
- [x] `Uploader` 组件的 `after-pick` prop
- [x] `Uploader` 组件的 `sortable` prop
- [x] `Table`/`Column` 组件的 `allowed-orders` prop
- [x] `Select` 组件的 `selected` slot
- [x] `Tree`/`Transfer` 组件的 `merge-checked` prop
- [x] `Progress` 组件的 `indeterminate` prop
- [x] `Dialog` 组件的 `disabled` prop
- [x] `v-drag.sort` 指令
- [x] 新增 `Cascader` 组件
